node {
    stages {
        stage('Install') {
            steps {
                sh 'cd client'
                sh 'npm i'
            }
        }
        stage('Build') { 
            steps {
                // Create Docker container 
                sh 'cd client'
                sh 'ng build --prod --aot --sm --progress=false'
            }
        }
        stage('Test') { 
            steps {
                // Run Unit testing
                sh 'cd client'
                sh 'ng test --progress=false --watch false'
            }
        }
        stage('Deploy') { 
            steps {
                // Deploy Docker container
                echo 'Deploying'
            }
        }
    }
}